name: Verify Linked Issue

on:
  pull_request: # Event
    types: # Actions
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  verify-linked-issue:
    name: Verify Pull Request references Issue
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
    steps:
      - uses: hattan/verify-linked-issue-action@v1.1.1
        id: verify_issue_reference
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Report no referenced issue
        if: steps.verify_issue_reference.outputs.has_linked_issues != 'true'
        run: exit 1;
