name: Validate PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure that a scope must always be provided.
          requireScope: true
          # If the PR contains one of these labels, the validation is skipped.
          ignoreLabels: |
            bot
            ignore-semantic-pull-request

